config/routes.rb
Rails.application.routes.draw do
  get 'game/index'

  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'welcome#index'

  
end

app/models/article.rb
class Article < ActiveRecord::Base

    # Define relationship with comments table, destroy comments related to article
    # when article is destroyed in the database. 
    has_many :comments, dependent: :destroy

    # Validate that title is present and at least 5 characters before attempting
    # to save to the database. 
    validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base

    # Define relationship to article table in database.
    belongs_to :article
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    # Require user authentication on every action but index and show
    http_basic_authenticate_with name: "newrelic", password: "minigolf", except: 
    [:index, :show]
    
    # Get array of all article objects
    def index
        @articles = Article.all
    end

    # Get article object by querying for the article id
    def show
        @article = Article.find(params[:id])
    end

    # Create a new article object and render the form
    def new
        @article = Article.new
    end

    # Get article object to be updated by querying for the article id and render
    # the edit form
    def edit
        @article = Article.find(params[:id])
    end

    # Take the object created in new and attempt to save it to the database, if 
    # successful redirect to show view, if not render the new form again
    def create
        @article = Article.new(article_params)
 
        if @article.save
            redirect_to @article
        else
            render "new"
        end
    end
    
    # Get article object from edit and attempt to update it in database, if 
    # successful, redirect to show view, if not render the edit form again
    def update
        @article = Article.find(params[:id])

        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end

    # Delete article in database
    def destroy
      @article = Article.find(params[:id])
      @article.destroy
     
      redirect_to articles_path
    end
    
    # Define article_params in order to both require and permit title and text
    private
      def article_params
        params.require(:article).permit(:title, :text)
      end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    # Require user authentication in order to delete a comment
    http_basic_authenticate_with name: "newrelic", password: "minigolf", only: :destroy

    # Get article object by querying for the article id, use the create method 
    # in the articles model to create an new comment in the database then 
    # redirect to article show view.
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end
    
    # Get article object by querying for the article id, get comment object by
    # querying for the comment in the article object that matches the comment
    # id. Delete that comment from the database and redirect to the article show view. 
    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end 
    
    # Define comment_params in order to both require and permit commenter and 
    # body text
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/game_controller.rb
class GameController < ApplicationController

  def index
    @players = ['Mikey', 'Robin', 'Jacob', 'Rebecca', 'Julian', 'Yvonne', 
                'Christine', 'Gina', 'Jim', 'Hilarie']
                
    @holes = ['Putt-Pong','Putt R. Mutt', 'Guess What? Chicken Putt!',
              'Snake Bite!','Right on Cue','Stargazer','Take It to the Grave',
              'Move Your Hole!','The Uncertainty Principle']
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    # Define index so welcome view will be rendered
    def index
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<!-- partial form view to be used by both the create new article view and the
edit article view -->

<%= form_for @article do |f| %>
 
  <!-- If the article can not be saved to the database, show error(s) messages
  so the user knows what need to change. -->
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Form input fields -->
<div class="well">

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-11 form-group">
      <h3><%= f.label :title %></h3>
      <%= f.text_field :title, class: "form-control"  %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-11 form-group">
      <h3><%= f.label :text %></h3>
      <%= f.text_area :text, rows: "15", class: "form-control" %>
    </div>
  </div>

  <%= f.submit %>

</div>
 
<% end %>

app/views/articles/_nav.html.erb
<!-- Nav bar partial view -->

<nav class="navbar navbar-default navbar-static-top overlay">
    <div class="navbar-header">
        <h2><%= link_to "Mini-Golf Enthusiasts", root_path , class: "logo" %></h2>
    </div>
</nav>

app/views/articles/edit.html.erb
<!-- Render partial nav view -->
<%= render "nav" %>

<div class="container-fluid">

    <h2>Enter edits below for: <%= @article.title %></h2>

    <%= link_to "Back to articles", article_path(@article), class: "back_link" %>

    <!--Render form partial for the edit method-->
    <%= render "form" %>

</div>

app/views/articles/index.html.erb
<!-- Render partial nav view -->
<%= render "nav" %>

<div class="container-fluid">

<div class="row">
  <div class= "col-xs-12 col-sm-12 col-md-6 col-md-offset-4">
    <h1 class="headline">Latest Mini-Golf Posts</h1>
  </div>
</div>


 <!-- For each article is articles array, render the following table row-->
  <% @articles.each do |article| %>
    <div class="well">

      <h2><%= article.title %></h2>

      <p><%= article.text[0..275] %> 
      <!-- Create link that links to article show view -->
      <%= link_to "Continue Reading", article_path(article) %> <p>
      
    </div>
  <% end %>


<%= button_to "Add a new article", new_article_path, :method => "get",
                class: "btn btn-success" %>

</div>

app/views/articles/new.html.erb
<!-- Render partial nav view -->
<%= render "nav" %>

<div class="container-fluid">

<%= link_to "Back to all articles", articles_path, class: "back_link" %>
    
    <h2>Add a New Mini-Golf Article</h2>

        <!--Render form partial for the new method-->
        <%= render "form" %> 
        
</div>

app/views/comments/_comment.html.erb
<!-- partial comment view -->

<div class="well">
        
        <h4><%= comment.commenter %></h4>
       
         
        <p> <%= comment.body %></p>
    
        <!-- Create link with "Destroy Comment" text that links to article show view 
        but first shows confirm window to confirm that user wants to delete the 
        comment. If they confirm, the delete method is executed before going to 
        the show view.-->
        <%= link_to "Delete", [comment.article, comment],
                    method: :delete,
                    data: { confirm: "Are you sure?" } %>
</div>

app/views/comments/_form.html.erb
<!-- partial form view for comments -->

<%= form_for([@article, @article.comments.build]) do |f| %>

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 form-group">
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 form-group">
      <%= f.label :body %><br>
      <%= f.text_area :body, class: "form-control"  %>
    </div>
  </div>
  
  <%= f.submit %>
  
<% end %>

app/views/game/_hole.html.erb
<!-- for each putt putt hole in the the holes array from the controller, 
create this div.  -->
<% @holes.each do |hole| %>

<div class="col-xs-12 col-sm-12 col-md-4">
    <div class="col-xs-10 col-xs-offset-1 hole_div">
      <h3 class="hole_name">  <%= hole %> </h3>
      <button class="btn btn-default btn-success btn-lg putt">Ready Set...Putt!</button>

      <table class="table table-striped table-condensed hole_table" >
        <th ><h3 class="name">Putter</h3></th>
        <th class="scoreheader"><h3>Score</h3></th>
      </table>
    </div>
</div>

<% end %>

app/views/game/index.html.erb
<nav class="navbar navbar-default navbar-static-top overlay">
  <div class="navbar-header">
    <h2><%= link_to "Mini-Golf Enthusiasts", root_path , class: "logo" %></h2>
  </div>
</nav>

<div class = "container-fluid" id="gamepage"> 
  <br>
  <i id="note">** Names borrowed from the "famous" <a href="walkerart.org/minigolf">
   Walker on the Green course</a> in Minneapolis."</i>  

  <!-- Leaderboard initial set up -->
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-4 col-md-offset-4">
      <h1 id="leaderheader"> LEADERBOARD </h1>
      <table class="table table-striped table-condensed" id="leader">
        <thead>
          <th><h3 class="name">Putter</h3></th>
          <th class="scoreheader"><h3>Overall Score</h3></th>
        </thead>

        </tbody>
          <% @players.each do |player| %>

            <tr class="player">
              <td><h4 class="name"> <%= player %> </h4></td>
              <td class="score"><h4>0</h4></td>
            </tr>
          <% end %>
        </tbody>
      
      </table>
    </div>
  </div>

  <!-- Use partial view to render a div for each hole -->
  <div class="row" id="main_game">
    <%= render "hole" %>
  </div>

  <!-- Game over button that is only visible after the 9th hole has been played -->
  <div class ="row"> 
    <div class="col-xs-12 col-sm-12 col-md-4 col-md-offset-8">
      <div class="col-xs-10 col-md-offset-1">
        <button class="btn btn-default btn-lg" id="top"> 
          <span class="glyphicon glyphicon-hand-up" aria-hidden="true"></span>
          Game Over! See the Winner! </button> 
      </div>
    </div> 
  </div>

</div><!-- end of container -->

<script>
$(document).ready(function(){
  // on initial load all putt buttons but the first are disabled
  $(".putt").prop("disabled",true);
  var firstButton = $(".putt").first();
  $(firstButton).prop("disabled",false);

  // hide the winner button until the 9th hole is played
  $("#top").hide();

  // Create initial zero scores for each player
  <% @players.each do |player| %>
    var <%= player %>OverallScore = 0;
  <% end %>

  // Function that will return a random putt number
  function getRandomPutt(min, max) {
    return Math.floor(Math.random() * (max-min)+min);
  }

  // Event handler when one of the putt buttons is clicked.
  $(".putt").click(function(evt){
    // disable the button that was just clicked
    $(this).prop("disabled",true);

    // identify and select the table right after the button that was clicked
    var holeTable = $(this).next("table");

    var leaderboard = [];

    <% @players.each do |player| %>
      // For each player, get a random number
      var putt = getRandomPutt(1,15);
      // Create a table row and with the players name and the putt score
      var htmlStr = "";
      htmlStr += "<tr class='player' style='display: none;'><td><h4 class='name'>";
      htmlStr += "<%= player %> </h4></td><td class='score'><h4>" + putt + "</h4></td></tr>";
      // Append the row to the table
      $(holeTable).append(htmlStr);

      // Add the putt number to the players current overall score.
      <%= player %>OverallScore += putt;
      // Create an object containing the players name and score. Push the object
      // to the leaderboard array that will be used to update the leaderboard.
      var player = {};
      player["name"] = "<%= player %>";
      player["score"] = <%= player %>OverallScore;
      leaderboard.push(player);

    <% end %>

    //Show each players score for that hole one by one, with added dramatic 
    // pause before, to represent putting time. 
    $(function() {
      i = 0;
      $(".player").each(function(i) {
      $(this).delay((i++) * 50).fadeTo(800, 100);})
    });

    // Sort the leaderboard array by player score
    leaderboard.sort(function(a, b) {
    return parseInt(a.score) - parseInt(b.score);
    });

    // Replace the Leaderboard table with new rows based on the sorted order of
    // the leaderboard array
    $("#leader tbody").replaceWith(function() {
      var newboard = "<tbody>"
      for (var i = 0; i < leaderboard.length; i++) {
        newboard += "<tr class='player'><td><h4 class='name'>" + leaderboard[i]['name'] + "</h4></td>";
        newboard += "<td class='score'><h4>" + leaderboard[i]['score'] + "</h4></td></tr>";
      }
      newboard += "</tbody>"
      return newboard;
    })

    // Check if there is a next hole div on the page, meaning you are not on 
    // hole 9, and if so make the button for the next hole clickable.
    var nextTable = $(this).parent("div").parent("div").next("div").children("div");
    if ($(nextTable).children(".putt").length > 0) {
      var nextButton = $(nextTable).children(".putt");
      $(nextButton).prop("disabled",false);
    }
    else {
      // Else, if you are on hole 9, show the button that will take you back to 
      // the top of the page and create a button to refresh the game. 
      $("#top").show();
      var PlayAgainBtn = '<%= button_to "Play again!", game_index_path, 
                             :method => "get", class: "btn btn-default btn-lg" %>'
                             
      if (leaderboard[0]["score"] !== leaderboard[1]["score"]) {
        // If there isn't a tie for first, color the winner's row(first row in leader table) 
        // red and add a congratulatory message with a button to refresh the game.
        var winnerRow = $("#leader tbody tr").first();
        $(winnerRow).css("color", "red");
        $("#leaderheader").prepend("<h2>" + leaderboard[0]["name"] + " is the winner!</h2>");
        $("#leaderheader").prepend(PlayAgainBtn);
        }
      else {
        // If there is a tie for first, color the both winners rows red and add 
        // a tie message with a button to refresh the game. Note, this could be
        // extended to check if more than two people tied, but statistically it
        // didn't seem probable.
        var winnerOne = $("#leader tbody tr").first();
        var winnerTwo = $(winnerOne).next("tr");
        $(winnerOne).css("color", "red");
        $(winnerTwo).css("color", "red");
        $("#leaderheader").prepend("<h2>" + leaderboard[0]["name"] + " and " + 
                                    leaderboard[1]["name"] +" tied!</h2>");
        $("#leaderheader").prepend(PlayAgainBtn);
        }
      }
    })
   
   // Event handler for winner button at the bottom of the page to take you 
   // back to the top of the page to see the leaderboard.
   $("#top").click(function(evt){ 
      $("body").scrollTop(0);
    });    
});
</script>

app/views/layouts/application.html.erb
<!-- base html template for all html views -->
<!DOCTYPE html>
<html>
    <head>
        <title>Mini-Golf Enthusiasts </title>
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
        <link href="https://fonts.googleapis.com/css?family=Fontdiner+Swanky" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
        <!--[if lt IE 9]>
            <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
            </script>
        <![endif]-->

    </head>

    <body>        
            <!-- Individual view contents will appear here. -->
            <%= yield %>
        
    </body>

</html>

app/views/welcome/index.html.erb
<!-- Homepage view -->
<div id="homepage" class ="container-fluid">
    <div class = "row">

        <div class="col-xs-12 col-sm-12 col-md-9">
            <h1>Mini-Golf Enthusiasts</h1>
            <h3>Because regular golf is too hard</h3>

            <%= button_to "Go the Blog", articles_path, :method => "get",
                class: "btn btn-success blog" %>
            <br>
            <%= button_to "Play a Game", game_index_path, :method => "get",
                class: "btn btn-success blog" %>
            
        </div>
    </div>
</div>